# Generated by Django 5.2.4 on 2026-07-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abha', '0001_initial'),
        ('patient', '0018_auto_20260704_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abhalink',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abha_link', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='otpsession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_sessions', to='patient.patient'),
        ),
    ]
