# Generated by Django 5.2.4 on 2025-08-05 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_alter_doctor_user_alter_nurse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Nurses'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'receptionist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
