# Generated by Django 5.2.4 on 2025-08-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_alter_nurse_user_alter_receptionist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
