# Generated by Django 5.2.4 on 2025-10-13 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_remove_patient_contact_number_remove_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='accepts_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
