# Generated by Django 4.2.20 on 2025-10-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_hospital_accepts_insurance_hospital_rating'),
    ]

    operations = [
    ]
