# Generated by Django 4.2.20 on 2025-10-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_seed_specializations'),
    ]

    operations = [
    ]
