# Generated by Django 4.2.20 on 2025-10-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0009_rename_sname_to_name'),
    ]

    operations = [
    ]
