# Generated by Django 4.2.20 on 2025-10-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0010_add_specialization_fields'),
    ]

    operations = [
        # Add new optional fields
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='specialization_icons/'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='icon_data',
            field=models.BinaryField(blank=True, null=True, help_text='Binary image data stored in database'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        # State-only rename to keep DB column name as "Sname"
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='specialization',
                    old_name='Sname',
                    new_name='sname',
                ),
                migrations.AlterField(
                    model_name='specialization',
                    name='sname',
                    field=models.CharField(max_length=100, unique=True, db_column='Sname'),
                ),
            ],
        ),
    ]


