# Generated by Django 5.2.4 on 2026-07-04 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0011_update_specialization_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
