# Generated by Django 5.2.4 on 2026-07-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0012_alter_hospital_rating_and_more'),
        ('records', '0002_alter_medicalrecord_patient'),
        ('abha', '0002_alter_abhalink_patient_alter_otpsession_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
