# Generated by Django 5.2.4 on 2026-07-05 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0014_alter_customuser_role_carecoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
