# Generated by Django 5.2.4 on 2025-09-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_abha_id'),
        ('doctor', '0002_remove_doctor_password_alter_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('diagnosis', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True, help_text='List medications with dosage and frequency')),
                ('tests_recommended', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
