# Generated by Django 5.2.4 on 2025-10-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_appointmentprescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contact_number',
        ),
    ]
