# Generated by Django 5.2.4 on 2025-10-28 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_add_doctor_fields'),
        ('patient', '0012_alter_patient_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Current status of the consent request', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the consent was requested')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the patient responded to the consent request', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the consent expires (if applicable)', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for requesting access to medical reports')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from patient')),
                ('doctor', models.ForeignKey(help_text='Doctor requesting access', on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests', to='doctor.doctor')),
                ('patient', models.ForeignKey(help_text='Patient whose reports are being accessed', on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Consent Request',
                'verbose_name_plural': 'Consent Requests',
                'ordering': ['-requested_at'],
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
