# Generated by Django 5.2.4 on 2026-07-04 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_consent'),
        ('patient', '0017_alter_wellnesslog_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('doctor', 'patient'), name='unique_active_consent'),
        ),
    ]
