# Generated by Django 5.2.4 on 2025-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_address_doctor_created_at_doctor_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepts_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
