# Generated by Django 5.2.4 on 2025-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='abha_id',
            field=models.CharField(default='', help_text='ABHA ID for the appointment', max_length=20, unique=True),
        ),
    ]
