# Generated by Django 5.2.4 on 2026-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_abha_id'),
        ('care', '0012_alter_hospital_rating_and_more'),
        ('doctor', '0006_alter_consent_unique_together_alter_doctor_rating_and_more'),
        ('patient', '0017_alter_wellnesslog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'rejected', 'expired']), _negated=True), fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_active_appointment_slot'),
        ),
    ]
