# Generated by Django 5.2.4 on 2026-07-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_unique_active_appointment_slot'),
        ('care', '0015_alter_customuser_contact_number_and_more'),
        ('doctor', '0006_alter_consent_unique_together_alter_doctor_rating_and_more'),
        ('patient', '0022_alter_patient_pincode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='appointment_appoint_5be6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor'], name='appointment_doctor__649ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='appointment_patient_94a7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
    ]
