# Generated by Django 5.2.4 on 2025-10-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_remove_nurse_password_nurse_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='contact_number',
        ),
    ]
