# Generated by Django 5.2.4 on 2026-07-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_remove_nurse_contact_number'),
        ('patient', '0021_alter_patientdocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(help_text='Clinical observation notes recorded by the nurse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='nurse.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patient.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
