# Generated by Django 5.2.4 on 2025-09-19 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0005_remove_patient_password_patient_user_and_more'),
        ('doctor', '0003_appointmentprescription'),
        ('patient', '0012_alter_patient_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teleconsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('meeting_link', models.URLField(blank=True, help_text='Video call meeting link', null=True)),
                ('meeting_id', models.CharField(blank=True, help_text='Meeting ID for video call', max_length=100, null=True)),
                ('meeting_password', models.CharField(blank=True, help_text='Meeting password', max_length=50, null=True)),
                ('symptoms', models.TextField(blank=True, help_text='Patient symptoms and concerns', null=True)),
                ('notes', models.TextField(blank=True, help_text="Doctor's notes during consultation", null=True)),
                ('prescription', models.TextField(blank=True, help_text='Prescription given during consultation', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultations', to='doctor.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultations', to='care.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultations', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Teleconsultation',
                'verbose_name_plural': 'Teleconsultations',
                'ordering': ['-created_at'],
            },
        ),
    ]
