# Generated by Django 5.2.4 on 2025-09-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_dob_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload your profile photo', null=True, upload_to='patient_photos/'),
        ),
    ]
