# Generated by Django 5.2.4 on 2025-09-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientdocument'),
    ]

    operations = [
    ]
