# Generated by Django 5.2.4 on 2025-09-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20250913_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDocument',
        ),
    ]
