# Generated by Django 5.2.4 on 2025-09-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_delete_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Document title or description', max_length=255)),
                ('document_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('scan_report', 'Scan Report'), ('prescription', 'Prescription'), ('medical_certificate', 'Medical Certificate'), ('discharge_summary', 'Discharge Summary'), ('insurance_document', 'Insurance Document'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(help_text='Upload your document', upload_to='patient_documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Additional details about the document', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Document verification status')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_extension', models.CharField(blank=True, help_text='File extension', max_length=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Patient Document',
                'verbose_name_plural': 'Patient Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
