# Generated by Django 5.2.4 on 2025-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patientdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocument',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes about this document', null=True),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='document_type',
            field=models.CharField(choices=[('report', 'Medical Report'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('scan', 'Scan/Imaging'), ('insurance', 'Insurance Document'), ('id_proof', 'ID Proof'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='file',
            field=models.FileField(help_text='Upload your document', upload_to='patient_documents/%Y/%m/'),
        ),
    ]
