# Generated by Django 5.2.4 on 2025-10-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_billingreceipt_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='patient',
        ),
        migrations.DeleteModel(
            name='BillingReceipt',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
