# Generated by Django 4.2.20 on 2025-10-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_feedback_doctor_remove_feedback_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medication name', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage amount', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_times_daily', 'Three Times Daily'), ('four_times_daily', 'Four Times Daily'), ('as_needed', 'As Needed'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='How often to take', max_length=20)),
                ('prescribed_date', models.DateField(help_text='Date prescribed')),
                ('prescribed_by', models.CharField(blank=True, help_text='Prescribing doctor', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Is medication currently active')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions')),
                ('side_effects', models.TextField(blank=True, help_text='Noted side effects')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patient.patient')),
            ],
            options={
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Name of the lab test', max_length=200)),
                ('test_date', models.DateField(help_text='Date test was performed')),
                ('result_value', models.CharField(help_text='Test result value', max_length=100)),
                ('normal_range', models.CharField(help_text='Normal range for this test', max_length=100)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical'), ('pending', 'Pending')], help_text='Result status', max_length=20)),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's interpretation")),
                ('lab_name', models.CharField(blank=True, help_text='Laboratory name', max_length=200)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patient.patient')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Management'), ('exercise', 'Exercise'), ('nutrition', 'Nutrition'), ('sleep', 'Sleep'), ('medication', 'Medication Adherence'), ('vitals', 'Vital Signs'), ('general', 'General Health')], help_text='Type of health goal', max_length=20)),
                ('title', models.CharField(help_text='Goal title', max_length=200)),
                ('description', models.TextField(help_text='Detailed goal description')),
                ('target_value', models.CharField(help_text='Target value to achieve', max_length=100)),
                ('current_value', models.CharField(blank=True, help_text='Current progress value', max_length=100)),
                ('start_date', models.DateField(help_text='Goal start date')),
                ('target_date', models.DateField(help_text='Goal target date')),
                ('is_achieved', models.BooleanField(default=False, help_text='Has goal been achieved')),
                ('is_active', models.BooleanField(default=True, help_text='Is goal currently active')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to='patient.patient')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WellnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_intake_glasses', models.IntegerField(default=0, help_text='Glasses of water consumed')),
                ('sleep_hours', models.DecimalField(decimal_places=1, help_text='Hours of sleep', max_digits=3)),
                ('steps_count', models.IntegerField(default=0, help_text='Number of steps taken')),
                ('mood_score', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')], help_text='Mood rating (1-5)')),
                ('exercise_minutes', models.IntegerField(default=0, help_text='Minutes of exercise')),
                ('stress_level', models.IntegerField(default=1, help_text='Stress level (1-5)')),
                ('notes', models.TextField(blank=True, help_text='Daily wellness notes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_logs', to='patient.patient')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['patient', '-date'], name='patient_wel_patient_1ed87c_idx')],
                'unique_together': {('patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure_systolic', models.IntegerField(help_text='Systolic blood pressure (mmHg)')),
                ('blood_pressure_diastolic', models.IntegerField(help_text='Diastolic blood pressure (mmHg)')),
                ('heart_rate', models.IntegerField(help_text='Heart rate (BPM)')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature (°F)', max_digits=4)),
                ('oxygen_saturation', models.IntegerField(help_text='Oxygen saturation (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='Weight (lbs)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patient.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='patient_vit_patient_5566d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('type', models.CharField(choices=[('appointment', 'Appointment'), ('medication', 'Medication'), ('health', 'Health'), ('system', 'System'), ('lab_result', 'Lab Result'), ('reminder', 'Reminder')], help_text='Notification type', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Has notification been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('action_url', models.URLField(blank=True, help_text='Optional action URL')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patient.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_read', '-created_at'], name='patient_not_patient_fb25c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('taken_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about taking medication')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='patient.medication')),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['medication', '-taken_at'], name='patient_med_medicat_a2d638_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient', 'is_active'], name='patient_med_patient_ddb6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['patient', '-test_date'], name='patient_lab_patient_e13cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='healthgoal',
            index=models.Index(fields=['patient', 'is_active'], name='patient_hea_patient_35d98d_idx'),
        ),
    ]
