# Generated by Django 5.2.4 on 2026-07-04 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_patient_date_of_birth_patient_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wellnesslog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='blood_pressure_diastolic',
            field=models.IntegerField(help_text='Diastolic blood pressure (mmHg)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='blood_pressure_systolic',
            field=models.IntegerField(help_text='Systolic blood pressure (mmHg)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='heart_rate',
            field=models.IntegerField(help_text='Heart rate (BPM)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='oxygen_saturation',
            field=models.IntegerField(help_text='Oxygen saturation (%)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='temperature',
            field=models.DecimalField(decimal_places=1, help_text='Temperature (°F)', max_digits=4, validators=[django.core.validators.MinValueValidator(90.0), django.core.validators.MaxValueValidator(110.0)]),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight (lbs)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AddConstraint(
            model_name='healthgoal',
            constraint=models.CheckConstraint(condition=models.Q(('target_date__gte', models.F('start_date'))), name='target_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='wellnesslog',
            constraint=models.UniqueConstraint(fields=('patient', 'date'), name='unique_patient_wellness_log'),
        ),
    ]
