# Generated by Django 5.2.4 on 2026-07-04 11:29

from django.db import migrations


def migrate_data(apps, schema_editor):
    CarePatient = apps.get_model('care', 'Patient')
    PatientPatient = apps.get_model('patient', 'Patient')
    MedicalRecord = apps.get_model('records', 'MedicalRecord')
    AbhaLink = apps.get_model('abha', 'AbhaLink')
    OtpSession = apps.get_model('abha', 'OtpSession')

    for care_p in CarePatient.objects.all():
        patient_p, created = PatientPatient.objects.get_or_create(
            user=care_p.user,
            defaults={
                'full_name': care_p.full_name,
                'gender': care_p.gender,
                'date_of_birth': care_p.dob,
                'dob': care_p.dob,
                'address': care_p.address,
                'city': care_p.city,
                'pincode': care_p.pincode,
                'abha_id': care_p.abha_id,
                'emergency_number': care_p.emergency_number,
                'blood_group': care_p.blood_group,
                'existing_condition': care_p.existing_condition,
                'allergies': care_p.allergies,
            }
        )
        if not created:
            if not patient_p.abha_id and care_p.abha_id:
                patient_p.abha_id = care_p.abha_id
            if not patient_p.date_of_birth and care_p.dob:
                patient_p.date_of_birth = care_p.dob
                patient_p.dob = care_p.dob
            if not patient_p.address and care_p.address:
                patient_p.address = care_p.address
            if not patient_p.city and care_p.city:
                patient_p.city = care_p.city
            if not patient_p.pincode and care_p.pincode:
                patient_p.pincode = care_p.pincode
            if not patient_p.emergency_number and care_p.emergency_number:
                patient_p.emergency_number = care_p.emergency_number
            if not patient_p.blood_group and care_p.blood_group:
                patient_p.blood_group = care_p.blood_group
            if not patient_p.existing_condition and care_p.existing_condition:
                patient_p.existing_condition = care_p.existing_condition
            if not patient_p.allergies and care_p.allergies:
                patient_p.allergies = care_p.allergies
            patient_p.save()

        MedicalRecord.objects.filter(patient_id=care_p.id).update(patient_id=patient_p.id)
        AbhaLink.objects.filter(patient_id=care_p.id).update(patient_id=patient_p.id)
        OtpSession.objects.filter(patient_id=care_p.id).update(patient_id=patient_p.id)


def reverse_migrate_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_wellnesslog_unique_together_and_more'),
        ('care', '0011_update_specialization_fields'),
        ('records', '0001_initial'),
        ('abha', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_migrate_data),
    ]

