# Generated by Django 5.2.4 on 2026-07-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_auto_20260704_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
