# Generated by Django 5.2.4 on 2026-07-04 17:53

import records.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_alter_notification_action_url_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocument',
            name='file',
            field=models.FileField(help_text='Upload your document', upload_to=records.utils.secure_patient_documents_path),
        ),
    ]
