# Generated by Django 5.2.4 on 2026-07-05 17:43

import django.core.files.storage
import pathlib
import records.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_alter_patient_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/Shru/Jeevan/jeevan/private_media')), upload_to='lab_results/'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='file',
            field=models.FileField(help_text='Upload your document', storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/Shru/Jeevan/jeevan/private_media')), upload_to=records.utils.secure_patient_documents_path),
        ),
    ]
