# Generated by Django 5.2.4 on 2026-07-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0015_alter_customuser_contact_number_and_more'),
        ('patient', '0023_alter_labresult_file_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='associated_hospitals',
            field=models.ManyToManyField(blank=True, related_name='patients', to='care.hospital'),
        ),
    ]
