# Generated by Django 5.2.4 on 2025-09-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_remove_receptionist_password_receptionist_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionist',
            old_name='contact_number',
            new_name='contact_no',
        ),
        migrations.AddField(
            model_name='receptionist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Experience in years'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='receptionist_photos/'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
