# Generated by Django 5.2.4 on 2025-09-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0003_auto_20250911_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='is_active',
        ),
    ]
