# Generated by Django 5.2.4 on 2025-09-11 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_remove_patient_password_patient_user_and_more'),
        ('receptionist', '0004_remove_receptionist_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionist',
            old_name='contact_no',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='address',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='qualification',
        ),
        migrations.AddField(
            model_name='receptionist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist', to='care.hospital'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'receptionist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
