# Generated by Django 5.2.4 on 2025-09-11 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_remove_patient_password_patient_user_and_more'),
        ('receptionist', '0005_rename_contact_no_receptionist_contact_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='receptionist_photos/'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionists', to='care.hospital'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'receptionist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
