# Generated by Django 5.2.4 on 2025-09-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0006_receptionist_email_receptionist_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='address',
            field=models.TextField(blank=True, help_text='Full address', null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational qualification', max_length=255, null=True),
        ),
    ]
