# Generated by Django 5.2.4 on 2025-10-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0007_receptionist_address_receptionist_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='email',
        ),
    ]
