# Generated by Django 5.2.4 on 2026-07-04 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0008_remove_receptionist_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='password',
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='address',
            field=models.TextField(blank=True, help_text='Full residential address (minimum 10 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth (age must be between 18-65 years)', null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience (0-50 years)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='full_name',
            field=models.CharField(help_text='Full name (letters, spaces, hyphens, apostrophes, and dots only)', max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, apostrophes, and dots.', regex="^[a-zA-Z\\s\\-\\'\\.]+$")]),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture (JPG, PNG, GIF - Max 5MB)', null=True, upload_to='receptionist_photos/'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational qualification (minimum 2 characters)', max_length=255, null=True),
        ),
    ]
