# Generated by Django 5.2.4 on 2026-07-04 17:53

import records.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=records.utils.secure_reports_path),
        ),
    ]
