# Generated by Django 5.2.4 on 2026-07-05 17:43

import django.core.files.storage
import pathlib
import records.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_medicalrecord_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='report_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/Shru/Jeevan/jeevan/private_media')), upload_to=records.utils.secure_reports_path),
        ),
    ]
