# Generated by Django 5.2.4 on 2026-07-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_medicalrecord_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='fhir_condition',
            field=models.JSONField(blank=True, help_text='FHIR Condition resource representing diagnosis (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='fhir_medication_request',
            field=models.JSONField(blank=True, help_text='FHIR MedicationRequest resource representing prescription (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='snomed_diagnosis_code',
            field=models.CharField(blank=True, help_text='SNOMED-CT Code for the main diagnosis', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='snomed_diagnosis_display',
            field=models.CharField(blank=True, help_text='SNOMED-CT Preferred Term / Display name', max_length=255, null=True),
        ),
    ]
